name: ZAP-Proxy

on:
  push:
    branches: ["tcc-usp"]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  zap_proxy:
    name: DAST - ZAP Proxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ github.sha }} .

      - name: Run application
        run: |
          docker run -d -p 8080:8080 --name reserva ${{ github.sha }}
          sleep 10
      - name: Zap Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: "http://localhost:8080"
